FROM golang:1.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 go build -o main -a -ldflags '-linkmode external -extldflags "-static"' .


FROM scratch
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.3 /lambda-adapter /opt/extensions/lambda-adapter
WORKDIR /app
COPY --from=builder /app/main .
COPY static/ static/
COPY templates/ templates/
EXPOSE 1323
CMD ["./main"]