// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"p-4\"><ul class=\"flex gap-4 justify-between\"><li hx-replace-url=\"/dashboard\" hx-get=\"/dashboard\" hx-target=\"#main-content\" class=\"flex flex-col justify-center items-center cursor-pointer\"><img class=\"h-5\" src=\"/static/img/home.svg\"> <span>Home</span></li><li hx-replace-url=\"/stats\" hx-get=\"/stats\" hx-target=\"#main-content\" class=\"flex flex-col justify-center items-center cursor-pointer\"><img class=\"h-5\" src=\"/static/img/stats.svg\"> <span>Stats</span></li><li hx-replace-url=\"/weight\" hx-get=\"/weight\" hx-target=\"#main-content\" class=\"flex flex-col justify-center items-center cursor-pointer\"><img class=\"h-5\" src=\"/static/img/scale.svg\"> <span>Weight</span></li><li hx-replace-url=\"/calories\" hx-get=\"/calories\" hx-target=\"#main-content\" class=\"flex flex-col justify-center items-center cursor-pointer\"><img class=\"h-5\" src=\"/static/img/food.svg\"> <span>Calories</span></li><li hx-replace-url=\"/settings\" hx-get=\"/settings\" hx-target=\"#main-content\" class=\"flex flex-col justify-center items-center cursor-pointer\"><img class=\"h-5\" src=\"/static/img/settings.svg\"> <span>Settings</span></li></ul></nav><script>\n\t\tfunction setStyles(){\n\t\t\tconst url = window.location.href.split(\"/\")[window.location.href.split(\"/\").length - 1];\n\t\t\tconst activeLink = document.querySelector(`li[hx-get=\"/${url}\"]`);\n\t\t\tactiveLink.style.textDecoration = \"underline\";\n\t\t\tactiveLink.style.textDecorationThickness = \"2px\";\n\t\t\tactiveLink.style.textDecorationColor = \"#2596be\";\n\t\t\tactiveLink.style.textUnderlineOffset = \"8px\";\n\t\t}\n\t\tsetStyles();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
